FROM ubuntu 
RUN apt-get update 
RUN apt-get install  default-jdk -y
RUN apt-get install  git-all -y 
RUN wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -
RUN echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list
RUN apt-get install \
    	apt-transport-https \
    	ca-certificates \
    	curl \
    	gnupg-agent \
    	software-properties-common

RUN apt-get install jenkins
RUN systemctl enable jenkins.service
RUN systemctl start jenkins.service

EXPOSE 80 
CMD [“-D”, “FOREGROUND”]


